name: Test Update
on:
  push:
    branches:
      - '**'
permissions:
  contents: write
  pull-requests: write
jobs:
  update-dependencies-files:
    uses: ./.github/workflows/reusable_update-dependencies-files.yml
    with:
      swift-version: "6.2.1"
      package-path: "./HelperTestPackage"
      dot-file: "./sample.dot"
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
