name: Test Update
on:
  push:
    branches:
      - '**'
    paths:
      - '**/Package.swift'
permissions:
  contents: write
  pull-requests: write
jobs:
  update-dependencies-files:
    uses: ./.github/workflows/reusable_update-dependencies-files.yml
    with:
      swift-version: "6.2.3"
      package-path: "./HelperTestPackage"
      dot-file: "./sample.dot"
      dot-derived-svg-file: "./sample.dot.svg"
      mermaid-file: "./sample.mmd"
      mermaid-derived-svg-file: "./sample.mmd.svg"
      mermaid-embedded-markdown-file: "./README.md"
      commit-pattern: via-pr
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
